# Zero CORE 2 - mods.toml

modLoader="javafml"
loaderVersion="[46,49)"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ZeroNoRyouki/ZeroCore2/issues"
logoFile="logo.png"

[[mods]]

	modId="zerocore"
	version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/ZeroNoRyouki/ZeroCore2/master/update.json"
    displayName="Zero CORE 2"
	authors="ZeroNoRyouki"
	description="Utility mod and multiblock API"

[[dependencies.zerocore]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.zerocore]]

	modId="forge"
	mandatory=true
    versionRange="[46.0.11,49)"
	ordering="NONE"
	side="BOTH"
